### ISSUE TITLE
请教下UnityNativeCamera android 系统上的相关问题

### ISSUE THREAD

**Issue by zhaoguomanong** [luoluoqixi/UnityCamera#2]
Hi
  我想请教下，这个相机的插件，是不是必须依赖于系统自带的内置相机app？ 我编译完了你的UnityCamera apk安装到android 平台，发现打开相机直接调用系统自带的相机app. 我们现在有个需求是用unity直接开发一个系统相机app, 包括录像和拍照功能，不太清楚您提到的UnityNativeCamera 能不能实现这些功能？ 如果仅仅是调用系统内置相机app来实现拍照和录像功能可能没法满足需求。

谢谢

**Comment by luoluoqixi** [comment]
这两个库应该都只是调用系统相机界面的，如果你想要把相机画面集成进Unity的UI，可以看看WebCamera，Unity实现的，如果想做更专业的相机功能感觉还是写原生平台代码或者寻找其他插件吧，比如很多AR插件有一套集成到UGUI的相机界面

**Comment by zhaoguomanong** [comment]
看来这插件没法满足需求， 有推荐的插件吗？ 我搜了下免费相机相关的插件也只找到UnityNativeCamera， 其他的大部分都收费的
